server:
  port: 8090
  servlet:
    context-path: /sign
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sign?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qazwsx
    jpa:
      hibernate:
          ddl-auto: create
      show-sql: true
